sudo: required
services:
  - docker

before_install:
  - docker build -t gaganbhullar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gaganbhullar/react-test npm run test

after_success:
  - docker build -t gaganbhullar/multi-client ./client
  - docker build -t gaganbhullar/multi-nginx ./nginx
  - docker build -t gaganbhullar/multi-server ./server
  - docker build -t gaganbhullar/multi-worker ./worker

  # log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push gaganbhullar/multi-client
  - docker push gaganbhullar/multi-nginx
  - docker push gaganbhullar/multi-server
  - docker push gaganbhullar/multi-worker